---
version: 0.0.1
ssh_user: akerl
domain: a-rwx.org
full_name: Les Aker
email: me@lesaker.org
api_ids:
  stackscript: 9930
  distribution: 132
  stock_kernel: 138
  pvgrub: 95
  finnix: 25665
stackscript: ./meta/stackscript
disks:
  - label: root
    size: 7168
    type: ext4
  - label: lvm
    size: 40960
    type: raw
...
