---
ssh_user: akerl
domain: a-rwx.org
full_name: Les Aker
email: me@lesaker.org
api_ids:
  stackscript: 9930
  distribution: 142
  stock_kernel: 138
  xen_kernel: 95
  kvm_kernel: 210
  finnix: 25665
stackscript: ./meta/stackscript
disks:
  - label: root
    size: 7168
    type: ext4
  - label: lvm
    size: 40960
    type: raw
networking:
  docker0_ipv6_prefix: 'fd00::'
...
