---
paths:
  device: /dev/xvdc
  mount: /mnt/dock0
  build_file: ./root.fs
  build: ./build
  package_list: ./packages
  overlay: ./overlay
  scripts: ./scripts
root_size: 4096
lvm:
  device: /dev/xvdd
  name: dock0
  lvs:
    cowland:
      size: 5G
      fs: ext4
    docker:
      size: 30G
      fs: ext4
domain: a-rwx.org
admin_email: admin@lesaker.org
kernel:
  configs: ./kernels
  tmpdir: ./tmp
  version: 3.13.1
  revision: 1
  initcpio_helpers: ./initcpio
  modules: 'base,udev,lvm2,dock0'
  options:
    root: /dev/xvda
    archisobasedir: /
    cow_device: /dev/dock0/cowland
    cowfile_size: 100
cleanup:
  users:
    - ftp
    - http
  paths:
    - srv/ftp
    - srv/http
    - etc/systemd/system/getty.target.wants/getty@tty1.service
    - etc/skel/.bashrc
    - etc/skel/.bash_logout
    - etc/skel/.bash_profile
templates:
  - etc/mail/exim.conf
  - etc/mail/aliases
  - etc/hostname
  - etc/hosts
  - etc/netctl/main
commands:
  chroot:
    - sed 's/^root::/root:x:/' /etc/shadow
    - usermod -s /usr/bin/zsh root
    - ln -s ../usr/share/zoneinfo/US/Eastern /etc/localtime
    - locale-gen
    - ln -s /root/.dotdotdot.conf /root/.../conf
    - /root/.../... update
    - /root/.../... install
    - /opt/scripts/script_sync /opt/scripts
    - /opt/scripts/key_sync /opt/keys/default /root/.ssh/authorized_keys quiet
...
