---
paths:
  output: ./build-cartman.tar.gz
hostname: cartman
networking:
  ipv4_addrs:
    - 139.162.27.7/24
    - 192.168.155.2/17
  ipv4_gateway: 139.162.27.1
  ipv6_addrs:
    - 2400:8901::f03c:91ff:fe18:7b45/64
  ipv6_gateway: fe80::1
...
