---
paths:
  output: ./build-olhado.tar.gz
hostname: olhado
networking:
  ipv4_addrs:
    - 70.85.129.127/24
    - 192.168.128.222/17
  ipv4_gateway: 70.85.129.1
  ipv6_addrs:
    - 2600:3c00::f03c:91ff:fe50:b02c/64
    - 2600:3c00:e001:9001::1/56
  ipv6_gateway: fe80::1
containers:
- name: dock0/blog
  external_ports:
  - internal: 80
- name: dock0/dns
  external_ports:
  - internal: 53
  - internal: 53
    protocol: udp
- name: dock0/committed
  external_ports:
  - internal: 80
    external: 8080
- name: dock0/hellolinodians
  envfile: hellolinodians
- name: dock0/redis
  bridge: fidelius
- name: dock0/fidelius
  external_ports:
  - internal: 80
    external: 1080
  bridge: fidelius
  envfile: fidelius
...
