---
paths:
  output: ./build-quara.tar.gz
hostname: quara
networking:
  ipv4_addrs:
    - 192.81.129.127/24
    - 192.168.167.222/17
  ipv4_gateway: 192.81.129.1
  ipv6_addrs:
    - 2600:3c01::f03c:91ff:fe50:b041/64
    - 2600:3c01:e001:9001::1/56
  ipv6_gateway: fe80::1
containers:
- name: dock0/blog
  ports:
  - internal: 80
- name: dock0/dns
  ports:
  - internal: 53
  - internal: 53
    protocol: udp
- name: dock0/committed
  ports:
  - internal: 80
    external: 8080
- name: dock0/hellolinodians
  envfile: hellolinodians
...
