---
paths:
  output: ./build-quim.tar.gz
hostname: quim
hypervisor: kvm
networking:
  ipv4_addrs:
    - 139.162.159.5/24
    - 192.168.159.2/17
  ipv4_gateway: 139.162.159.1
  ipv6_addrs:
    - 2a01:7e01::f03c:91ff:fee4:4c52/64
    - 2a01:7e01:e001:9::1/64
  ipv6_gateway: fe80::1
...
